shinyOptions(cache = cachem::cache_disk("./app_cache/cache/"))
library(readxl)
library(memoise)
library(SingleCellExperiment)
library(org.Mm.eg.db)
library(scater)
library(scran)
library(pheatmap)
library(limma)
library(edgeR)
library(dynamicTreeCut)
library(cluster)
library(batchelor)

library(BiocManager)
options(repos = BiocManager::repositories())
library(cowplot)
library(shiny)
library(ggplot2)
library(Seurat)
library(shinythemes)
library(TissueEnrich)
library(SummarizedExperiment)
library(SingleCellExperiment)
library(igraph)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(org.Hs.eg.db)
library(karyoploteR)
library(shinyalert)
library(dorothea)
library(textshape)
library(tidyr)
library(tidyverse)
library(reshape2)
library(data.table)
library(networkD3)
library(ggplot2)
library(shinyFiles)
library(dorothea)
library(bcellViper)
library(dplyr)
library(viper)
library(cli)
library(harmony)
library(rtracklayer)

library(shiny)
library(Seurat)
library(ggthemes)
library(shinythemes)
library(shinycustomloader)
library(shinyjs)
library(igraph)
library(shinybusy)
library(XVector)
library(shinyWidgets)
library(shinyalert)
library(shinyFiles)
library(memisc)
library(AUCell)
library(dorothea)
library(networkD3)
library(bcellViper)
library(dplyr)
library(viper)

library(ggplot2)
library(ggplot2)
library(GGally)
library(GSEABase)
library(limma)
library(reshape2)
library(data.table)
library(knitr)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)
library(stringr)
library(NMF)
library(rsvd)
library(RColorBrewer)
library(Matrix)
library(data.table)
library(NMF)
library(shinythemes)
library(shinyBS)
library(DESeq2)
library(MAST)
abc <- readRDS("R/abc.rds")
xyz <- readRDS("R/xyz.rds")
pqr <- readRDS("R/pqr.rds")
gensets <- readRDS("R/gensets.rds")
gse<-readRDS("R/gse.RDS")
doro<-readRDS("R/dorothea_regulon_human.RDS")
meta<-readRDS("R/meta.rds")
